name: Auto PR Generator
on:
  schedule:
    - cron: "0 * * * *"   # Weekdays 9 AM to 5 PM, excluding Sunday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      # - name: Random delay
      #   run: |
      #     # Random delay between 30 minutes and 4 hours
      #     delay_minutes=$((RANDOM % 210 + 30))
      #     echo "Waiting $delay_minutes minutes before creating PR..."
      #     sleep $((delay_minutes * 60))
      - name: Make dummy change
        run: |
          echo "Update at $(date)" >> DUMMY.md
          git config --global user.name "le0623"
          git config --global user.email "leonel.lasso210@gmail.com"
          branch="auto-pr-$(date +%s)"
          git checkout -b $branch
          git add DUMMY.md
          git commit -m "chore: auto update $(date)"
          git push origin $branch
      - name: Create Pull Request
        run: |
          gh pr create --title "chore: auto update" --body "Automated PR to keep activity going" --base main --head $branch
        env:
          GITHUB_TOKEN: ${{ github.token }} 