name: Auto PR Generator
on:
  schedule:
    - cron: "0 * * * *"   # once every hour
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make dummy change
        run: |
          echo "Update at $(date)" >> DUMMY.md
          git config --global user.name "le0623"
          git config --global user.email "leonel.lasso210@gmail.com"
          branch="auto-pr-$(date +%s)"
          git checkout -b $branch
          git add DUMMY.md
          git commit -m "chore: auto update $(date)"
          git push origin $branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto update"
          branch: ${{ github.ref_name }}
          base: main
          title: "chore: auto update"
          body: "Automated PR to keep activity going"
          delete-branch: true 