name: Auto Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash